[{"ContainerToolsException.Message":"Não é possível determinar se o Docker está atualmente configurado para executar contêineres do Windows ou Linux. Verifique se o Docker está instalado e sendo executado localmente.","ContainerToolsException.ErrorCode":"","ContainerToolsException.StackTrace":"","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.InnerException":"Microsoft.VisualStudio.Containers.Tools.Common.ContainerToolsException: docker.errors.DockerException: Error while fetching server API version: 500 Server Error: Internal Server Error (\"b'open \\\\\\\\.\\\\pipe\\\\docker_engine_linux: O sistema n\\xc3\\xa3o pode encontrar o arquivo especificado.'\")\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.DockerComposeClient.<ExecuteAsync>d__9.MoveNext()\r\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.DockerComposeClient.<DownAsync>d__6.MoveNext()\r\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.DockerWorkspace.<ComposeDownContainersAsync>d__26.MoveNext()\r\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.BuildTasks.DockerBuildTask.<ExecuteAsync>d__30.MoveNext()\r\nCódigo de erro: DT1001\r\nGravidade: Error\r\nLinha de comando: docker-compose  -f \"D:\\Estudo\\ParcelamentoAPI\\docker-compose.yml\" -f \"D:\\Estudo\\ParcelamentoAPI\\docker-compose.override.yml\" -f \"D:\\Estudo\\ParcelamentoAPI\\obj\\Docker\\docker-compose.vs.release.partial.g.yml\" -p dockercompose15561821388792318508 --no-ansi kill\r\nCódigo de saída do comando: -1\r\nSaída de comando: \r\nErro de comando: [24392] Failed to execute script docker-compose\r\nTraceback (most recent call last):\r\n  File \"site-packages\\docker\\api\\client.py\", line 259, in _raise_for_status\r\n  File \"site-packages\\requests\\models.py\", line 941, in raise_for_status\r\nrequests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localnpipe/version\r\nDuring handling of the above exception, another exception occurred:\r\nTraceback (most recent call last):\r\n  File \"site-packages\\docker\\api\\client.py\", line 205, in _retrieve_server_version\r\n  File \"site-packages\\docker\\api\\daemon.py\", line 181, in version\r\n  File \"site-packages\\docker\\api\\client.py\", line 265, in _result\r\n  File \"site-packages\\docker\\api\\client.py\", line 261, in _raise_for_status\r\n  File \"site-packages\\docker\\errors.py\", line 31, in create_api_error_from_http_exception\r\ndocker.errors.APIError: 500 Server Error: Internal Server Error (\"b'open \\\\\\\\.\\\\pipe\\\\docker_engine_linux: O sistema n\\xc3\\xa3o pode encontrar o arquivo especificado.'\")\r\nDuring handling of the above exception, another exception occurred:\r\nTraceback (most recent call last):\r\n  File \"docker-compose\", line 3, in <module>\r\n  File \"compose\\cli\\main.py\", line 67, in main\r\n  File \"compose\\cli\\main.py\", line 123, in perform_command\r\n  File \"compose\\cli\\command.py\", line 69, in project_from_options\r\n  File \"compose\\cli\\command.py\", line 132, in get_project\r\n  File \"compose\\cli\\docker_client.py\", line 43, in get_client\r\n  File \"compose\\cli\\docker_client.py\", line 170, in docker_client\r\n  File \"site-packages\\docker\\api\\client.py\", line 188, in __init__\r\n  File \"site-packages\\docker\\api\\client.py\", line 213, in _retrieve_server_version\r\ndocker.errors.DockerException: Error while fetching server API version: 500 Server Error: Internal Server Error (\"b'open \\\\\\\\.\\\\pipe\\\\docker_engine_linux: O sistema n\\xc3\\xa3o pode encontrar o arquivo especificado.'\")\r\n"}]